server:
  port: ${PORT:8989}

management:
  port: 8990

eureka:
  client:
    serviceUrl:
       defaultZone: ${vcap.services.eureka-service-discovery.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    preferIpAddress: true

turbine:
  #clusterNameExpression: new String("default")
  aggregator:
    clusterConfig: MENU-SERVICE,WHATS-FOR-DINNER
  appConfig: menu-service,whats-for-dinner
  instanceInsertPort: false
  instanceUrlSuffix:
    MENU-SERVICE: :9180/hystrix.stream
    WHATS-FOR-DINNER: :9181/hystrix.stream
    #default: :9180/hystrix.stream   # 'default' equals CLUSTER NAME

spring:
  rabbitmq:
    addresses: ${vcap.services.cloudamqp-wfd-resiliency.credentials.uri}

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
management:
  port: -1
turbine:
  instanceUrlSuffix: /hystrix.stream
